# Generated by Django 4.0.4 on 2022-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField()),
                ('branch', models.CharField(choices=[('1', 'CSE'), ('2', 'EC'), ('3', 'EE'), ('4', 'ME'), ('5', 'CE')], default='----', max_length=100)),
                ('year', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default='----', max_length=100)),
            ],
        ),
    ]
