# Generated by Django 4.0.4 on 2022-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data1',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data1',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='----', max_length=100),
        ),
    ]
