# Generated by Django 4.0.4 on 2022-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_data1_branch_alter_data1_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('ec', 'EC'), ('ee', 'EE'), ('me', 'ME'), ('ce', 'CE')], default='---', max_length=100),
        ),
    ]
