# Generated by Django 4.0.4 on 2022-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_data1_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adname', models.CharField(max_length=100)),
                ('adpass', models.CharField(default=0, max_length=100)),
                ('mdses', models.CharField(max_length=100)),
            ],
        ),
    ]
